### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shaj13** [shaj13/raft#1]
### TODO 
- [x] add tcp rpc 
- [x] check the conf change v2 
- [ ] Repair wall 
- [ ] add more logs.

**Comment by shaj13** [comment]
both TCP and conf change 2 are still, under consideration
